---
- name: Creating Chache lock
  file: path=/ansible state=directory

- name: Checking File apt_needs_update
  stat: path=/ansible/apt_updated
  register: apt_updated

- name: Display apt_needs_update
  debug: msg="DHPARAM exists {{ apt_updated.stat.exists }}"

- name: Updating Apt [A bit lengthy]
  apt: update_cache=yes
  when: apt_updated.stat.exists != True

- name: Registering that apt is updated
  file: path=/ansible/apt_updated state=touch
  when: apt_updated.stat.exists != True
