---
# IRC Configs
irc_subdomain: irc
irc_server_description: Just a server
irc_network_name: SomeNet

irc_pid_file: /var/run/inspircd/inspircd.pid

irc_admin_fullname: Admin Adminovich
irc_admin_nick: admin
irc_admin_email: nope@nope.net
